win_acl.ps1 modified to have reset func., check_mode, environment string support, and right handling corrected
ansible-collections/ansible.windows pull request #129
Opened 2020-11-16 12:01 UTC by placame

##### SUMMARY

I've corrected the removing of rights, with post check for any remaining ACE and reporting if unsuccessful.
Added the requested reset functionality,
Added the requested support for environment variable in path,
Added check_mode support.
Also updated the doc win_acl.py

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

Executed some test with below playbook:
````
---
- hosts: win-test1.adtest.celab.ibm.cloud
  gather_facts: no
  tasks:
    - name: Query ACL
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL
    - debug:
        var: GetACL.stdout_lines
    - name: Query ChildACL
      win_shell: (get-acl c:\TestFldr\SubFldr\ChildFldr).AccessToString
      register: GetChildACL
    - debug:
        var: GetChildACL.stdout_lines
    - name: Remove standard user access
      win_acl:
        path: "%SystemDrive%\\TestFldr\\SubFldr"
        user: Users
        rights: ReadAndExecute
        type: allow
        state: absent
      register: SetACL
      ignore_errors: yes
    - debug:
        var: SetACL
    - name: Query ACL1
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL1
    - debug:
        var: GetACL1.stdout_lines
    - name: add Read and Execute rights to Built-in Users
      win_acl:
        path: c:\TestFldr\SubFldr
        user: Users
        rights: ReadAndExecute
        type: allow
        state: present
    - name: Query ACL2
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL2
    - debug:
        var: GetACL2.stdout_lines
    - name: add Write rights to Built-in Users group
      win_acl:
        path: c:\TestFldr\SubFldr
        user: Users
        rights: Write
        type: allow
        state: present
    - name: Query ACL31
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL31
    - debug:
        var: GetACL31.stdout_lines
    - name: Query ChildACL31
      win_shell: (get-acl c:\TestFldr\SubFldr\ChildFldr).AccessToString
      register: GetChildACL31
    - debug:
        var: GetChildACL31.stdout_lines
    - name: revoke the previously added Write rights from Built-in Users group
      win_acl:
        path: c:\TestFldr\SubFldr
        user: Users
        rights: Write
        type: allow
        state: absent
      ignore_errors: yes
    - name: Query ACL32
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL32
    - debug:
        var: GetACL32.stdout_lines
    - name: add Read and Execute rights to TestUser
      win_acl:
        path: c:\TestFldr\SubFldr
        user: TestUser
        rights: ReadAndExecute
        type: allow
        state: present
    - name: Query ACL4
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL4
    - debug:
        var: GetACL4.stdout_lines
    - name: Query ChildACL4
      win_shell: (get-acl c:\TestFldr\SubFldr\ChildFldr).AccessToString
      register: GetChildACL4
    - debug:
        var: GetChildACL4.stdout_lines
    - name: add Modify rights to TestUser
      win_acl:
        path: c:\TestFldr\SubFldr
        user: TestUser
        rights: Modify
        type: allow
        state: present
    - name: Query ACL41
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL41
    - debug:
        var: GetACL41.stdout_lines
    - name: Query ChildACL41
      win_shell: (get-acl c:\TestFldr\SubFldr\ChildFldr).AccessToString
      register: GetChildACL41
    - debug:
        var: GetChildACL41.stdout_lines
    - name: revoke Modify rights from TestUser
      win_acl:
        path: c:\TestFldr\SubFldr
        user: TestUser
        rights: Modify
        type: allow
        state: absent
    - name: Query ACL42
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL42
    - debug:
        var: GetACL42.stdout_lines
    - name: restore the expected state
      win_acl:
        path: c:\TestFldr\SubFldr
        user: TestUser
        rights: ReadAndExecute
        type: allow
        state: present
    - name: Query ACL43
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL43
    - debug:
        var: GetACL43.stdout_lines
    - name: add Write rights to TestUser
      win_acl:
        path: c:\TestFldr\SubFldr
        user: TestUser
        rights: Write
        type: allow
        state: present
    - name: Query ACL44
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL44
    - debug:
        var: GetACL44.stdout_lines
    - name: revoke Write rights from TestUser
      win_acl:
        path: c:\TestFldr\SubFldr
        user: TestUser
        rights: Write
        type: allow
        state: absent
    - name: Query ACL45
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL45
    - debug:
        var: GetACL45.stdout_lines
    - name: Reset ACL
      win_acl:
        path: c:\TestFldr\SubFldr
        state: reset
      register: ReSetACL
      ignore_errors: yes
    - debug:
        var: ReSetACL
    - name: Query ACL5
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL5
    - debug:
        var: GetACL5.stdout_lines
    - name: Reset ACL on root (M:\)
      win_acl:
        path: m:\
        state: reset
      register: ReSetACL
      ignore_errors: yes
    - debug:
        var: ReSetACL
    - name: Query ACL6
      win_shell: (get-acl c:\TestFldr\SubFldr).AccessToString
      register: GetACL6
    - debug:
        var: GetACL6.stdout_lines

````

The result:
```paste below

PLAY [win-test1.adtest.celab.ibm.cloud] ****************************************

TASK [Query ACL] ***************************************************************
changed: [win-test1.adtest.celab.ibm.cloud]

TASK [debug] *******************************************************************
ok: [win-test1.adtest.celab.ibm.cloud] => {
    "GetACL.stdout_lines": [
        "NT AUTHORITY\\SYSTEM Allow  FullControl",
        "BUILTIN\\Administrators Allow  FullControl",
        "BUILTIN\\Users Allow  ReadAndExecute, Synchronize",
        "BUILTIN\\Users Allow  AppendData",
        "BUILTIN\\Users Allow  CreateFiles",
        "CREATOR OWNER Allow  268435456"
    ]
}

TASK [Query ChildACL] **********************************************************
changed: [win-test1.adtest.celab.ibm.cloud]

TASK [debug] *******************************************************************
ok: [win-test1.adtest.celab.ibm.cloud] => {
    "GetChildACL.stdout_lines": [
        "NT AUTHORITY\\SYSTEM Allow  FullControl",
        "BUILTIN\\Administrators Allow  FullControl",
        "BUILTIN\\Users Allow  ReadAndExecute, Synchronize",
        "BUILTIN\\Users Allow  AppendData",
        "BUILTIN\\Users Allow  CreateFiles",
        "CREATOR OWNER Allow  268435456"
    ]
}

TASK [Remove standard user access] *********************************************
fatal: [win-test1.adtest.celab.ibm.cloud]: FAILED! => {"changed": false, "msg": "Users still has CreateFiles, AppendData, ReadAndExecute, Synchronize rights! Actual rights: Allow: ReadAndExecute, Synchronize: Inherited, ContainerInherit, ObjectInherit; Allow: AppendData: Inherited, ContainerInherit; Allow: CreateFiles: Inherited, ContainerInherit; ", "stderr": "Users still has CreateFiles, AppendData, ReadAndExecute, Synchronize rights!", "stderr_lines": ["Users still has CreateFiles, AppendData, ReadAndExecute, Synchronize rights!"]}
...ignoring

TASK [debug] *******************************************************************
ok: [win-test1.adtest.celab.ibm.cloud] => {
    "SetACL": {
        "changed": false,
        "failed": true,
        "msg": "Users still has CreateFiles, AppendData, ReadAndExecute, Synchronize rights! Actual rights: Allow: ReadAndExecute, Synchronize: Inherited, ContainerInherit, ObjectInherit; Allow: AppendData:  [...]

2020-11-24 03:09 UTC, jborean93 requested changes
I've left a few comments but as the PR stands now it will require a few things before we could look at merging it in. This module isn't the easiest to understand and unfortunately isn't tested too well which makes it hard to review these changes.

What I recommend is to split up each of the features you want to introduce into smaller PRs. Creating a separate PR for the each of the following will make it a lot easier for us to review and eventually merge in the changes:

* Doc updates
* Support for env vars in the path
* Check mode
* `state: reset` functionality

By splitting up the code we can merge in your changes piece by piece and potentially a lot quicker than trying to make a massive change all at once. It also makes the history a lot easier to understand by seeing each change as a separate layer rather than mixed together.

The last thing I should mention is that any new functionality in the code should have some integration tests to test the new functionality. This is a hard requirement and we won't be merging any PRs related to code changes without tests.

If you need help with trying to add integration tests I'm more than happy to help where I can. For now you can find our current tests at https://github.com/ansible-collections/ansible.windows/tree/main/tests/integration/targets/win_acl.

2020-11-25 14:11 UTC, placame commented on plugins/modules/win_acl.ps1
> +$path = (New-Object -ComObject Wscript.Shell).ExpandEnvironmentStrings($path)
Will this `-type "path"` accept registry paths as well?

2020-11-29 11:37 UTC, placame commented on plugins/modules/win_acl.ps1
> +# Revorked the logic to more exact handle of rights and proper return values,
I suppose my changes are substantial, as I've completely re-wrote the full logic to be able to gracefully fail when an inherited rights needed to be revoked. Also the 'reset' functionality is important thing. So added myself to the list, and removed everything else.

2020-11-29 11:38 UTC, placame commented on plugins/modules/win_acl.ps1
> -$path = Get-AnsibleParam -obj $params -name "path" -type "str" -failifempty $true
I've restructured the script so the parameter usage is now kept together as much as possible.

2020-11-29 11:39 UTC, placame commented on plugins/modules/win_acl.ps1
> +	  if($check_mode){
Re-worked this check_mode logic, now it does not change anything.

2020-11-29 11:40 UTC, placame commented on plugins/modules/win_acl.ps1
> +$path = (New-Object -ComObject Wscript.Shell).ExpandEnvironmentStrings($path)
I'd rather keep the type as string and perform later the necessary expansions to have more control over the process.

2020-11-29 12:57 UTC, placame commented
@jborean93 
I'd like to ask your help regarding the integration tests.
The current integration tests are not intended to show results of the new functionalities, also not showing the result of code correction regarding inherited rights.
Should I some way copy the current tests, and modify it to show the missing parts, or add new parts to the existing tests?
Can you help me with a way of executing the current integration tests on a local environment?

2020-11-29 19:38 UTC, jborean93 commented
> Should I some way copy the current tests, and modify it to show the missing parts, or add new parts to the existing tests?

You should leave the existing tests as they are today and just add more tests for your use case. Usually what we try to encourage for tests is to do the following:

```yaml
- name: run test in check mode
  win_acl:
    ...
  check_mode: yes
  register: scenario_check

-name: get result of run test in check mode
  win_shell: ...
  register: scenario_actual_check

- name: assert run test in check mode
  assert:
    that:
    # Verifies in check mode that it reported a change but didn't actually change the underlying resource
    - scenario_check is changed
    - scenario_actual_check.stdout == ...

- name: run test
  win_acl:
    ...
  register: scenario

-name: get result of run test
  win_shell: ...
  register: scenario_actual

- name: assert run test
  assert:
    that:
    # Verifies it reported a change and changed the resource to what we expected
    - scenario is changed
    - scenario_actual.stdout == ...

- name: run test idempotent
  win_acl:
    ...
  register: scenario_again

- name: assert run test idempotent
  assert:
    that:
    # On a 2nd run the task should not report a change
    - not scenario_again is changed
```

Usually I only have a check mode test for a few of them, or just one scenario that I know exercises the check mode code itself. The `win_shell` task is meant to get the actual state of the resource. Usually I just get the object output it as json then use `scenario_result.stdout | from_json` to be able to parse it in Ansible. I would recommend having a look at [win_certificate_store](https://github.com/ansible-collections/ansible.windows/tree/main/tests/integration/targets/win_certificate_store) and [win_dns_client](https://github.com/ansible-collections/ansible.windows/tree/main/tests/integration/targets/win_dns_client) for an example of some tests.

> Can you help me with a way of executing the current integration tests on a local environment?

Yep, all you need to do is place a file at `tests/integration/inventory.winrm` with the content

```ini
[windows]
my-host

[windows:vars]
ansible_user=username
ansible_password=password
ansible_connection=winrm
...
```

You will need to set whatever vars Ansible needs to connect to the host. You don't need to use the `winrm` connection plugin, just any one that Ansible can use to connect to your Windows host. Basically you should be able to do `ansible -i tests/integration/inventory.winrm windows -m win_ping` with that inventory file.

Let me know if you have any more questions.

2020-11-30 11:23 UTC, placame commented
@jborean93 
I've created some integration test. 
Find the test in this archive: 
[win_acl_integration_test.zip](https://github.com/ansible-collections/ansible.windows/files/5615626/win_acl_integration_test.zip)
TestResult.txt contains the output of: `ansible-playbook -i hosts ./win_acl_tests.yml >./TestResult.txt`
Let me know if any other thing, or more test would be required.
Or the tests should be executed with `-vvvv` option

2021-01-25 13:07 UTC, placame commented
@jborean93 
Any news or progress? 

I cannot split it into smaller changes as the solution for the new requirements are based on the changes in the main logic correcting errors in the original method.

2021-02-15 12:08 UTC, placame commented
@jborean93 ??

2021-03-18 14:40 UTC, placame commented
Hi @jborean93 ,
Ok, so here is the misunderstandings. The main purpose of my development was to correct the **errors** in the original code / **logic**. the added features are only secondary things. But correcting the original faulty code and logic makes it absolutely necessary to change almost the whole code, at least the part which hosted the faulty logic. You cannot except correcting a faulty logic with very similar code.

2021-03-18 18:53 UTC, jborean93 commented
That's the thing you are correcting some behaviour but adding new features. They are in no way related, you can do 1 without the other. To implement reset behaviour you don't need check mode, environment support doesn't need reset or check mode and vice versa. Putting it all together just makes it a whole lot harder for myself to review.

I know it's not ideal but these are supported modules so we need to treat it with a higher standard and higher scrutiny when compared to `community.windows`. This means a proper reivew which right now just isn't feasible with everything bundled together.

2021-03-19 09:24 UTC, placame commented
Ok, I'll open new pull requests for the stages. first the correction of the faulty logic.

2021-03-19 09:24 UTC, closed without merging