Add more detail about list arguments
ansible-collections/ansible.windows pull request #220
Opened 2021-05-13 09:27 UTC by owvarley

Including guidance from https://github.com/ansible/ansible/issues/50221#issuecomment-449199876 regarding the handling of list arguments. 

##### SUMMARY
I've spent quite a lot of time trying to figure out an issue regarding the use of list arguments with win_package. This [issue](https://github.com/ansible/ansible/issues/50221#issuecomment-449199876) had some really good advice from @jborean93 on how to properly use list arguments and I thought this would be a useful addition to the documentation just in case anyone else runs into something similar.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
ansible.windows.win_package

##### ADDITIONAL INFORMATION

The following task will fail with a return code of 87.
```- name: Install MSBuild Tools
  win_package:
    path: "https://download.visualstudio.microsoft.com/download/pr/9665567e-f580-4acd-85f2-bc94a1db745f/3580c7d8c43782aebab3af6db6e46e0f89752a96336f9518d3a10f407f4048af/vs_BuildTools.exe"
    product_id: '{D1437F51-786A-4F57-A99C-F8E94FBA1BD8}'
    arguments: 
    - --norestart
    - --passive
    - --wait
    - --add Microsoft.Net.Component.4.6.1.TargetingPack
    - --add Microsoft.Net.Component.4.6.TargetingPack
    - --add Microsoft.Net.Component.4.8.TargetingPack
    - --add Microsoft.Net.Component.4.8.SDK
    - --add Microsoft.VisualStudio.Component.NuGet.BuildTools
    - --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64
    - --add Microsoft.VisualStudio.Component.Windows10SDK.18362
    - --add Microsoft.VisualStudio.Component.TeamOffice.BuildTools
    - --add Microsoft.VisualStudio.Component.Roslyn.Compiler
    - --add Microsoft.VisualStudio.Component.Roslyn.LanguageServices
```

If you follow the guidance and example now added to the documentation the below changes will allow the task to run successfully:

```
- name: Install MSBuild Tools using correct list arguments
  win_package:
    path: "https://download.visualstudio.microsoft.com/download/pr/9665567e-f580-4acd-85f2-bc94a1db745f/3580c7d8c43782aebab3af6db6e46e0f89752a96336f9518d3a10f407f4048af/vs_BuildTools.exe"
    product_id: '{D1437F51-786A-4F57-A99C-F8E94FBA1BD8}'
    arguments: 
    - --norestart
    - --passive
    - --wait
    - --add 
    - Microsoft.Net.Component.4.6.1.TargetingPack
    - --add
    - Microsoft.Net.Component.4.6.TargetingPack
    - --add
    - Microsoft.Net.Component.4.8.TargetingPack
    - --add
    - Microsoft.Net.Component.4.8.SDK
    - --add
    - Microsoft.VisualStudio.Component.NuGet.BuildTools
    - --add
    - Microsoft.VisualStudio.Component.VC.Tools.x86.x64
    - --add
    - Microsoft.VisualStudio.Component.Windows10SDK.18362
    - --add
    - Microsoft.VisualStudio.Component.TeamOffice.BuildTools
    - --add
    - Microsoft.VisualStudio.Component.Roslyn.Compiler
    - --add
    - Microsoft.VisualStudio.Component.Roslyn.LanguageServices
```

2021-05-15 02:44 UTC, jborean93 requested changes
The rst pages are automatically generated from the module docs themselves. To make these changes you will have to apply them to the `win_package.py` file https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_package.py.

2021-05-15 08:55 UTC, owvarley commented
> The rst pages are automatically generated from the module docs themselves. To make these changes you will have to apply them to the `win_package.py` file https://github.com/ansible-collections/ansible.windows/blob/main/plugins/modules/win_package.py.

Sure @jborean93, I've done that now. Do I need to generate the docs as part of the pull request or is that done automatically as part of the merge?

2021-05-20 05:51 UTC, jborean93 approved these changes

2021-05-20 05:51 UTC, jborean93 commented
Thanks, the rst docs will be re-generated at the next release.

2021-05-20 05:51 UTC, merged