Added depth parameter to win_uri ConvertTo-Json call
ansible-collections/ansible.windows pull request #587
Opened 2024-02-26 07:59 UTC by thomasriera-akkodis

Added depth parameter to win_uri ConvertTo-Json call

##### SUMMARY
When using the win_uri module to send a json object, win_uri uses the ConvertTo-Json method. 

This method has a currently  unused parameter called Depth which represents the maximum depth of nested children to parse.
(https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-7.4#-depth)

This parameter's default value is 2, so the method does not correctly convert json objects with a higher depth.

I set it to a default of 20 which should be enough for most cases, or at least more useful than the default of 2.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_uri.ps1

##### ADDITIONAL INFORMATION
To reproduce the bug : send a json object with more than 2 levels of nesting using win_uri. The method will seem to work but the sent object will be incomplete.

With this change, the module can correctly send json objects with up to 20 levels of nesting.

2024-02-27 19:07 UTC, jborean93 requested changes
Thanks for the PR here, I've added a tiny suggestion that adds a comment explaining why it is ok to add the custom depth.

For us to merge this PR we do need 2 extra things here

+ A changelog fragment
+ Some tests for this scenario

The changelog fragment is documented under https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment, this feature would come under `minor_changes` and would be placed in https://github.com/ansible-collections/ansible.windows/tree/main/changelogs/fragments

The tests for `win_uri` are located at https://github.com/ansible-collections/ansible.windows/blob/main/tests/integration/targets/win_uri/tasks/main.yml. You would probably want something similar to https://github.com/ansible-collections/ansible.windows/blob/c207ed49ddf73f152f56817787824a2c4ba93226/tests/integration/targets/win_uri/tasks/main.yml#L328-L342 just with a more nested object structure as a new test.

Please let me know if you need any help with the above and I'm happy to point you in the right direction.

2024-02-27 19:07 UTC, jborean93 commented on plugins/modules/win_uri.ps1
> +        $body_string = ConvertTo-Json -InputObject $body -Compress -Depth 20
```suggestion
        # The body comes from Ansible so it is safe to exceed the normal depth of 2
        $body_string = ConvertTo-Json -InputObject $body -Compress -Depth 20
```

2024-03-05 19:23 UTC, jborean93 commented
@thomasriera-akkodis do you mind if I try and push some changes to get the tests working, I'm hoping to include this in the next release of this collection which I'm planning on doing soon.

2024-03-06 09:21 UTC, thomasriera-akkodis commented
@jborean93

I think everything should be okay now. Happy to see this change coming soon, I'll be able to remove my dirty workaround from my servers.

2024-03-06 18:42 UTC, jborean93 approved these changes
Thanks for working on this, the changes look great!

2024-03-06 18:43 UTC, merged