win_get_url - Make checksum work more like ansible.builtin.get_url
ansible-collections/ansible.windows pull request #718
Opened 2024-12-30 14:19 UTC by KBjorndal-VizRT

##### SUMMARY

Makes checksum handling behave more like ansible.builtin.get_url

Fixes #717 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

win_get_url

##### ADDITIONAL INFORMATION

I'm not 100% sure about the logic to trigger collecting `$dest_checksum`, it is technically called in some circumstances it wasn't before, though if I read the code right that was only in error cases since all normal exits would calculate it at the end of the script.

2025-01-07 21:01 UTC, jborean93 requested changes
The changes you've added here look good. Appreciate you updating the docs and adding the changelog fragment but are you also able to add a test for this specific scenario. We currently have some tests with the `checksum` option under https://github.com/ansible-collections/ansible.windows/blob/main/tests/integration/targets/win_get_url/tasks/tests_checksum.yml but it doesn't look like there are any ones for idempotency checking when `force: false` is set.

If you need help with any of this please let me know and I can guide you where I can.

2025-01-08 13:39 UTC, KBjorndal-VizRT commented
> The changes you've added here look good. Appreciate you updating the docs and adding the changelog fragment but are you also able to add a test for this specific scenario. We currently have some tests with the `checksum` option under https://github.com/ansible-collections/ansible.windows/blob/main/tests/integration/targets/win_get_url/tasks/tests_checksum.yml but it doesn't look like there are any ones for idempotency checking when `force: false` is set.

I added a test for the behaviour where it shouldn't do any download if checksum already matches.

Tried a few different ways but can't think of how to make an automated test for the other part. As far as I can see httpbin only sends 304 replies for the /cache endpoint, which otherwise returns dynamic data so it's impossible to make it emulate the case where we have a file that differs by checksum but the If-Modified-Since logic would say there is nothing new at the URL.

2025-01-08 14:08 UTC, KBjorndal-VizRT commented
Not sure what the failing check here is about, is it related to the PR or some CI infrastructure?

2025-01-09 02:55 UTC, jborean93 commented
> I added a test for the behaviour where it shouldn't do any download if checksum already matches.

Thanks, appreciate it.

> Tried a few different ways but can't think of how to make an automated test for the other part. As far as I can see httpbin only sends 304 replies for the /cache endpoint, which otherwise returns dynamic data so it's impossible to make it emulate the case where we have a file that differs by checksum but the If-Modified-Since logic would say there is nothing new at the URL.

I think that's fine to ignore for now, if we get any future regressions we can look at potentially spinning up a custom HTTP endpoint just as a test but I think that's overkill for now.

> Not sure what the failing check here is about, is it related to the PR or some CI infrastructure?

There seems to be some trouble with Zuul so the failure is unrelated here.

2025-01-09 02:55 UTC, jborean93 approved these changes

2025-01-09 02:55 UTC, merged